mixin Api {
  String get url => 'http://vlaw.thefuturevision.com:3000/api';
  // String get url => 'http://79.137.27.182:3000/api';
  String get loginApi => '$url/auth/login';
  String get deactivate => '$url/auth/deactivate';
  String get activate => '$url/auth/activate';
  String get clientTotal => '$url/client/?total=true&view=List';
  String get Addclient => '$url/client/';
  String get clientSearch => '$url/client/?total=true&search=';
  String get clientTotalNoBeg => '$url/client/?total=true';
  String get clientById => '$url/client/';
  String get fileById => '$url/case/';
  String get workById => '$url/work/';
  String get qadieaById => '$url/stage/';
  String get session => '$url/session/';
  String get Crudsession => '$url/session/';
  String get sessionUpdate => '$url/session/';
  String get work => '$url/work/';
  String get adDsession => '$url/session/31';
  String get Moaeed => '$url/appointment/';
  String get schedule => '$url/schedule';
  String get agencyTotal => '$url/agency/?total=true';
  String get employeeTotal => '$url/employee/?total=true';
  String get informingCase => '$url/informing/?total=true&CAS_ID_PK=';
  String get executeCase => '$url/execute/?total=true&CAS_ID_PK=';
  String get warningCase => '$url/warning/?total=true&CAS_ID_PK=';
  String get stageCase => '$url/stage/?total=true&CAS_ID_PK=';
  String get sessionCase => '$url/session/?total=true&view=List&CAS_ID_PK=';
  String get sessionStage => '$url/session/?total=true&view=List&STG_ID_PK=';
  String get sessionType => '$url/constraint/session-type';
  String get workType => '$url/constraint/work-type?total=true';
  String get workKind => '$url/constraint/work-kind';
  String get sessionDescion =>
      '$url/constraint/session-decision?total=true&SES_DECISION_STATUS=true';
  String get sessionPlace =>
      '$url/constraint/session-place?total=true&SES_PLACE_STATUS=true';
  String get sessionRoll =>
      '$url/constraint/session-role?total=true&SES_ROLL_STATUS=true';
  String get nationality => '$url/constraint/nationality?total=true';
  String get Addnationality => '$url/constraint/nationality';
  String get AddSessionType => '$url/constraint/session-type';
  String get AddSessionPlace => '$url/constraint/session-place';
  String get AddSessionRole => '$url/constraint/session-role';
  String get AddworkLink => '$url/constraint/work-kind';
  String get AddworkType => '$url/constraint/work-type';
  String get Addcompany => '$url/constraint/company-type';
  String get company => '$url/constraint/company-type?total=true';
  String get workHomeTotal => '$url/work/?total=true';
  String get contrcatTotal => '$url/contract/?total=true';
  String get moaeedtTotal => '$url/appointment/?total=true';
  String get moaeedtSearch => '$url/appointment/?total=true&search=';
  String get agencySearch => '$url/agency/?total=true&search=';
  String get contractSearch => '$url/contract/?total=true&search=';
  String get moaeedtType => '$url/constraint/appointment-type?total=true';
  String get fileTotal => '$url/case/?total=true';
  String get fileSearch => '$url/case/?total=true&search=';
  String get qadieaTotal => '$url/stage/?total=true';
  String get search => '$url/search/';
  String get sessionTotal => '$url/session/?total=true';
  String get wariningTotal => '$url/warning/?total=true';
  String get ExecuteTotal => '$url/execute/?total=true';
  String get InformingTotal => '$url/informing/?total=true';
  String get workTotal => '$url/work/?total=true&CAS_ID_PK=';
  String get dailyUpdatesWork => '$url/daily-update/work/?date=';
  String get dailyUpdatesSession => '$url/daily-update/session/?date=';
  // String get reminderAgency => '$url/reminder/agency/?type=';
  String get reminderAgency => '$url/reminder/agency/';

  String get reminderCases => '$url/reminder/cases/';
  String get reminderClient => '$url/reminder/client/';
  String get reminderContract => '$url/reminder/contract/';
  String get reminderEmployee => '$url/reminder/employee/';
  String get reminderexcute => '$url/reminder/execute/';
  String get reminderSession => '$url/reminder/session/';
  String get reminderWarning => '$url/reminder/warning';
  String get reminderWork => '$url/reminder/work/';
  String get chartFiles => '$url/chart/file/?';
  String get chartStage => '$url/chart/stage/?';
  String get chartSession => '$url/chart/session/?';
  String get chartAccount => '$url/chart/account/?';
  String get chartWork => '$url/chart/work/?';
}
